//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectorioTelefonico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int id_tel { get; set; }
        public string telefono1 { get; set; }
        public Nullable<int> id_contacto { get; set; }
    
        public virtual Contacto Contacto { get; set; }
    }
}
