//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectorioTelefonico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Contacto = new HashSet<Contacto>();
        }
    
        public int id_user { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> creation_dt { get; set; }
        public Nullable<System.TimeSpan> creation_time { get; set; }
        public Nullable<System.DateTime> update_dt { get; set; }
        public Nullable<System.TimeSpan> update_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto { get; set; }
    }
}
